# Generated by Django 3.1.5 on 2021-01-14 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='menu',
            new_name='category',
        ),
    ]
