# Generated by Django 3.1.5 on 2021-01-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210116_0513'),
        ('product', '0002_reviewreply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewReply',
            new_name='Reply',
        ),
        migrations.AlterModelTable(
            name='reply',
            table='replies',
        ),
    ]
