# Generated by Django 3.1.5 on 2021-01-13 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210113_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.image'),
        ),
    ]
