# Generated by Django 3.1.5 on 2021-01-14 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210114_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='main_category',
        ),
    ]
