# Generated by Django 3.1.5 on 2021-01-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210115_2037'),
        ('product', '0004_auto_20210116_2132'),
    ]

    operations = [
    ]
