# Generated by Django 3.1.5 on 2021-01-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coupon',
            field=models.ManyToManyField(through='user.UserCoupon', to='user.Coupon'),
        ),
    ]
