# Generated by Django 3.1.5 on 2021-01-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='coupon',
            new_name='coupons',
        ),
    ]
