# Generated by Django 3.1.5 on 2021-01-14 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210113_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='description',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='name',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='address_en',
        ),
        migrations.AddField(
            model_name='membership',
            name='discount_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='grade',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.membership'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
