# Generated by Django 3.1.5 on 2021-01-14 07:53

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210114_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='grade',
            field=models.CharField(default='silver', max_length=800),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=800, validators=[user.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, validators=[user.validators.validate_password]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=800, validators=[user.validators.validate_phone_number]),
        ),
    ]
