# Generated by Django 3.1.5 on 2021-01-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210120_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coupons',
        ),
    ]
