# Generated by Django 3.1.5 on 2021-01-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210120_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='count',
            new_name='quantity',
        ),
    ]
