# Generated by Django 3.1.5 on 2021-01-21 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210120_0311'),
        ('order', '0005_auto_20210120_0310'),
    ]

    operations = [
    ]
